# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a4ab4dd33ec8aff242d2041edb5abe768c8c0a3f1c1c97cb0a46681282e9406fe8aa8c08bc63f6fb2aa0c02d6c84131d26ed11096944b93f313a198cefdf429

test:
  secret_key_base: b3693a420081a34cd3876d0e798e121f96544fba4a174390d30ac971d2c13fe1a8c67cee689affad77b5bd1a0c4dafe9b94b9710bfe12141b9ef2f9ebee1a3d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
